apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-conntrack
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-conntrack
subjects:
- kind: ServiceAccount
  name: prometheus-conntrack
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: prometheus-conntrack
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-conntrack
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - pods
  verbs:
  - get
  - list
